### ISSUE TITLE
tray application icon

### ISSUE THREAD

**Issue by gustavomassa** [LennardKittner/HyperXCloudIIWireless#2]
Hello, first thank you very much for this awesome contribution.

I'm having an issue with the tray application icon, where the headset icon is located/loaded on the code?
I'm using the release version, already compiled binary.
![image](https://github.com/LennardKittner/HyperXCloudIIWireless/assets/16235598/a78ef0f4-c2c5-4208-b0fd-71f26b7cf463)

**Comment by LennardKittner** [comment]
Nice. I am happy that the issue got resolved. Thank you for posting a solution.
