### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by ddm90** [LennardKittner/HyperXCloudIIWireless#4]
Hi, i'm having a problem with the Panel tray icon app.
The CLI app works perfectly, but the GUI tray one never appears in my panel tray (Linux Mint 21.3 Cinnamon).

The terminal stays like this:
![image](https://github.com/LennardKittner/HyperXCloudIIWireless/assets/32983681/4eba8b0b-2ba8-4c3f-8c1f-6d3a2064209f)

I believe the app is getting battery status, because if i run it without sudo command, it shows multiple errors trying to get information.
So the app is running, just not showing in my panel tray.

Thanks in advance for any possible solution.

**Comment by LennardKittner** [comment]
Hi, thank you for your interest in my app. Have you added the rules as described [here](https://github.com/LennardKittner/HyperXCloudIIWireless?tab=readme-ov-file#udev-linux-only). If you did, you should not need to use sudo. Maybe using sudo causes some problems with the tray icon. I have only tested KDE Plasma so far.

**Comment by LennardKittner** [comment]
Good to hear :).
Someone else had the same issue #2. As I mentioned in that issue, I have no idea why the icon is not shown. I just tell the tray library to display a headset icon.

Maybe the library does not support your desktop environment, or you don't have a headset icon in your theme.
